//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kithen_Fergis.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punkt_fidachi
    {
        public double Пункт_выдачи { get; set; }
        public Nullable<double> Индекс { get; set; }
        public string Город { get; set; }
        public string Адрес { get; set; }
    }
}
